language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # download Miniconda 3
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # echo helpful info for debugging
  - conda info -a
  # create the conda env
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pandas pytest
  - conda activate test-env
  - python setup.py install
script:
  - pytest
